### ISSUE TITLE
图片失效

### ISSUE THREAD

**Issue by wasamtc** [Vay-keen/Machine-learning-learning-notes#30]
图片失效了，希望作者可以补充下

**Comment by Enki08** [comment]
这是来自QQ邮箱的自动回复邮件。您好，您的邮件我已收到，我会尽快给您回复。

**Comment by TerryA1Guai** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by TerryA1Guai** [comment]
您的邮件已查收，会尽快处理，辛苦了！谢谢！李镇东（机械56）机械工程学院|西安交通大学|地址：西安市碑林区咸宁西路28号|邮编：710049School of Mechanical Engineering.|Xi'an Jiaotong University.|Zip:710049Address:No.28 Weat Xianning Road,Xi'an,shanxi,P.R. ChinaQQ:97353872

**Comment by wasamtc** [comment]
不好意思是vpn的问题
